1
Wrong number of arguments: call(foo,[2])